### ISSUE TITLE
[Question] Other Linker/Librarian flags ?

### ISSUE THREAD

**Issue by rvi** [neonichu/MobileVLCKit-Sample-Thingy#1]
Hi,

Thanks for this example.

I'm trying to integrate VLC in my apps and I've got undefined symbols  while building for x86_64.
It looks like a C++ lib is missing. ([Full log here](https://gist.github.com/rvi/daf067c404ca38218c90))

Did you experience similar issues ?

In your project you link with some frameworks (see image below), in other linker flags and other Librarian Flags.

Did you do something to get them here ? Or just running `pod install` ?

On my project I've got nothing

![screen shot 2015-01-21 at 18 42 24](https://cloud.githubusercontent.com/assets/1455122/5841881/a9ec592e-a1a0-11e4-8358-7c1728adf458.png)

Thanks for reading !

**Comment by neonichu** [comment]
Yup, they're from the Pods XCConfig - do you use a custom config or override the flags in your project?

**Comment by rvi** [comment]
Nope, nothing like that. I finally add the libraries to link with manually,  change the C++ compiler to libstc++, and add an Objective-C++ file, and it finally worked! :-)

Thanks !

**Comment by rvi** [comment]
Btw, I enjoyed your lightning talk at DotSwift :)

**Comment by neonichu** [comment]
Cool and thanks :)

![](http://38.media.tumblr.com/ccb1db010b487cb45d05ab826bc43298/tumblr_mp5561k8T21sy3onao1_500.gif)
